"""added column

Revision ID: 560e7084b1c7
Revises: 0484b49d5bdb
Create Date: 2024-02-22 16:21:40.482273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560e7084b1c7'
down_revision = '0484b49d5bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joke_type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_column('joke_type')

    # ### end Alembic commands ###
